import { AI_FLOORPLAN_SKILL_PACK } from './ai-floorplan-skill-pack'
import { AI_WALLS_SYSTEM_PROMPT, AI_WALLS_USER_PROMPT } from './ai-walls-prompt'

function assert(cond: boolean, msg: string) {
  if (!cond) throw new Error(msg)
}

assert(AI_WALLS_SYSTEM_PROMPT.includes('简体中文'), 'think in Chinese')
assert(AI_WALLS_SYSTEM_PROMPT.includes(AI_FLOORPLAN_SKILL_PACK), 'skill pack inlined')
assert(AI_FLOORPLAN_SKILL_PACK.includes('outerLoop'), 'wall skill')
assert(AI_FLOORPLAN_SKILL_PACK.includes('客厅'), 'room skill')
assert(AI_FLOORPLAN_SKILL_PACK.includes('bed'), 'furniture skill')
assert(AI_FLOORPLAN_SKILL_PACK.includes('openings'), 'openings in skill pack')
assert(AI_FLOORPLAN_SKILL_PACK.includes('衣帽间'), 'closet is not a wall')
assert(AI_FLOORPLAN_SKILL_PACK.includes('拐弯'), 'keep facade jogs')
assert(AI_FLOORPLAN_SKILL_PACK.includes('目标效果'), 'gold-standard target')
assert(AI_FLOORPLAN_SKILL_PACK.includes('门洞'), 'door gaps')
assert(AI_WALLS_USER_PROMPT(18670).includes('18670'), 'user width')
assert(AI_WALLS_USER_PROMPT().includes('40～70'), 'user prompt door gap width')
assert(AI_WALLS_USER_PROMPT().includes('四壁'), 'user prompt room walls')
assert(AI_WALLS_SYSTEM_PROMPT.includes('禁止只复述规则'), 'thinking must not echo slogans')
assert(AI_WALLS_USER_PROMPT().includes('图像宽高'), 'user prompt in-bounds')
assert(AI_FLOORPLAN_SKILL_PACK.includes('左侧立面'), 'left facade jogs')
assert(AI_FLOORPLAN_SKILL_PACK.includes('图像内'), 'coords in image')
assert(AI_WALLS_SYSTEM_PROMPT.includes('openings'), 'openings in schema')
assert(AI_WALLS_USER_PROMPT().includes('openings'), 'user prompt openings')
assert(AI_FLOORPLAN_SKILL_PACK.includes('双线'), 'double-line walls to centerline')
assert(AI_FLOORPLAN_SKILL_PACK.includes('图签'), 'drop title block')
assert(AI_FLOORPLAN_SKILL_PACK.includes('门弧'), 'door swing')
assert(AI_FLOORPLAN_SKILL_PACK.includes('推拉门'), 'sliding door')
assert(AI_FLOORPLAN_SKILL_PACK.includes('至少一扇门'), 'one door per room')
assert(AI_FLOORPLAN_SKILL_PACK.includes('40～70'), 'skill door gap width')
assert(AI_FLOORPLAN_SKILL_PACK.includes('四壁'), 'skill room four walls')
assert(!AI_FLOORPLAN_SKILL_PACK.includes('宁可漏一段短内墙'), 'do not skip partitions')
assert(AI_WALLS_USER_PROMPT().includes('推拉门'), 'user prompt sliding doors')
assert(AI_FLOORPLAN_SKILL_PACK.includes('软件界面'), 'drop CAD chrome')
assert(AI_WALLS_USER_PROMPT().includes('AutoCAD'), 'user prompt CAD screenshot')
assert(
  AI_WALLS_USER_PROMPT(18670, { width: 1280, height: 831 }).includes('1280×831'),
  'prompt includes real image size'
)
assert(AI_WALLS_USER_PROMPT().includes('1920×1200'), 'forbid invented resolution')
assert(AI_FLOORPLAN_SKILL_PACK.includes('示意矩形'), 'forbid cartoon outer loop')
assert(AI_FLOORPLAN_SKILL_PACK.includes('承重墙'), 'bearing walls after outer')
assert(AI_FLOORPLAN_SKILL_PACK.includes('拐弯'), 'bearing wall jogs')
assert(AI_WALLS_USER_PROMPT().includes('承重墙'), 'user prompt bearing walls')
assert(AI_WALLS_USER_PROMPT().includes('拐弯'), 'user prompt bearing jogs')
assert(AI_WALLS_SYSTEM_PROMPT.includes('粗承重墙'), 'think bearing walls first')
assert(AI_WALLS_USER_PROMPT().includes('尺寸数字'), 'reject dimension strings')
assert(AI_FLOORPLAN_SKILL_PACK.includes('尺寸界线'), 'skill drops dimension lines')
assert(AI_FLOORPLAN_SKILL_PACK.includes('短横回头'), 'skill keeps L-return')
assert(AI_FLOORPLAN_SKILL_PACK.includes('主卫'), 'skill master bath walls')
assert(AI_FLOORPLAN_SKILL_PACK.includes('目录横条'), 'skill room labels off title strip')
assert(AI_WALLS_USER_PROMPT().includes('短横回头'), 'user prompt L-return')
assert(AI_WALLS_USER_PROMPT().includes('主卫'), 'user prompt master bath')
assert(AI_WALLS_USER_PROMPT().includes('目录横条'), 'user prompt off title strip')
assert(AI_WALLS_SYSTEM_PROMPT.includes('目录横条'), 'think room labels in rooms')
assert(AI_WALLS_USER_PROMPT().includes('尺寸链'), 'reject printed size chain as outerLoop')
assert(AI_WALLS_USER_PROMPT().includes('斜线填充'), 'hatched bearing walls')
assert(AI_FLOORPLAN_SKILL_PACK.includes('黄线'), 'yellow is OCR only')
assert(AI_FLOORPLAN_SKILL_PACK.includes('斜线填充'), 'skill hatched bearing')
console.log('ai-walls-prompt.test ok')
